name = "server"
main = "src/index.ts"
compatibility_date = "2024-12-02"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "d1-test"
database_id = "dfcc5a3e-0c3a-4f53-92c8-b0cecd321603"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1